# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
    imageName: 'httplistener:$(build.buildId)'
    dockerId: 'nwestfall'

jobs:
- job: linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: docker build -f Dockerfile -t $(dockerId)/$(imageName)-linux .
    displayName: 'docker build'
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)
    displayName: 'docker push'
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - script: docker build -f Dockerfile -t $(dockerId)/$(imageName)-windows .
    displayName: 'docker build'
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)
    displayName: 'docker push'
